# Generated by Django 2.1.2 on 2018-10-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=30)),
                ('cover_image', models.ImageField(default='default.png', max_length=128, upload_to='')),
                ('VIP_only', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(max_length=30)),
                ('state', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.Filter')),
                ('style_template', models.ImageField(max_length=128, upload_to='')),
                ('brush_size', models.IntegerField(default=512)),
                ('brush_intensity', models.IntegerField(default=512)),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_class', to='web.Class'),
        ),
    ]
