# Generated by Django 2.1.2 on 2018-10-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181021_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='detail',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
