# Generated by Django 2.1.2 on 2018-10-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181021_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='VIP_only',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='description',
        ),
        migrations.AddField(
            model_name='filter',
            name='brush_intensity',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='filter',
            name='brush_size',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='filter',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='style_template',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
