# Generated by Django 2.1.2 on 2018-10-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181021_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='upload_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
